---
abstract: 'Define delete triggers'
author:
  - 'Maroš Kollár'
build_requires:
  Class::C3: 0
  DBD::SQLite: 0
  ExtUtils::MakeMaker: 6.42
  Test::Exception: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
  Test::Warn: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.82'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-Class-DeleteAction
no_index:
  directory:
    - inc
    - t
requires:
  DBIx::Class: 0
  SQL::Abstract: 0
  perl: 5.6.0
  version: 0
resources:
  license: http://dev.perl.org/licenses/
version: 1.030
